import { Inter } from "next/font/google";
import "@/styles/globals.css";
import PrivateRoute from "@/helpers/PrivateRoute";
import Providers from "../providers";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Push",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${poppins.variable}`} lang="en">
      <body >
        <Providers>
          <PrivateRoute>{children}</PrivateRoute>
        </Providers>
      </body>
    </html>
  );
}
